# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 933e76fe09a295f85e150b628dd04a86492a23384562af6c99149735b0195ec3192b47a6222a1a166da066565b8d9994691d24ad2b6e578cc6c51c98ba4f264e

test:
  secret_key_base: 4d7bf4edee637a6628572767e1c96ab671e66e7edf589dd7ee76a499c40ead7eeba4eccdd0bc56935de6654c6720f807857fb7b9d2f37c7935034b50661313f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
